server:
  port: 8312

#开发配置
spring:
  datasource:
    url: jdbc:mysql://10.10.208.194:3306/example_db?useUnicode=true&characterEncoding=utf-8
    username: root
    # Jasypt加密 可到common-utils中找到JasyptUtil加解密工具类生成加密结果 格式为ENC(加密结果)
    password: urcs@2018
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    # 自动生成表结构
    generate-ddl: true
    hibernate:
      ddl-auto: none
  thymeleaf:
    cache: false
  #jwt
  jwt:
    secret: mySecret
    header: Authorization
    expiration: 604800
    tokenHead: Bearer

  #redis
  redis:
    host: 10.10.208.194
    port: 6379
  # spring session使用存储类型
  session:
    store-type: redis
secst:
  # 全局限流
  rateLimit:
    enable: true
    # 每1秒内
    timeout: 1000
    # 总限制100个请求
    limit: 100
  # token交互方式
  token:
    # 默认JWT 启用Redis后设置为true后，token将存入redis，并具有单点登录功能
    redis: true
  # token过期时间（分钟）
  tokenExpireTime: 60
  # 用户选择保存登录状态对应token过期时间（天）
  saveLoginTime: 7
  # 限制用户登陆错误次数（次）
  loginTimeLimit: 10
  # 错误超过次数后多少分钟后才能继续登录（分钟）
  loginAfterTime: 10

ignored:
  urls:
    - /login
    - /login.html
    - /loginerror.html
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /**/v2/api-docs
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
    - /test/**